FROM node:18

# Solana CLI
RUN sh -c "$(curl -sSfL https://release.solana.com/v1.14.1/install)"
ENV PATH="/root/.local/share/solana/install/active_release/bin:$PATH"

# Rust
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
RUN echo 'source $HOME/.cargo/env' >> $HOME/.bashrc

# Anchor
RUN cargo install --git https://github.com/project-serum/anchor avm --locked --force
RUN avm install latest
RUN avm use latest

EXPOSE 3000
EXPOSE 49153

WORKDIR /solana
